name: cicd
on:
    push:
        paths:
            - 'src/**'
        branches:
            - main
jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Shortem commit hash
              shell: bash
              run: | 
                echo "COMMIT_ID=${GITHUB_SHA::7}" >> "$GITHUB_ENV"
            
            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: k0dy/python-app:${{ env.COMMIT_ID }}
    cd:
        needs: ci
        runs-on: self-hosted
        steps:
            - name: Install Argocd CLI
              shell: bash
              run: |
                mkdir -p $HOME/bin

                curl -sSL -o $HOME/bin/argocd \
                  https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64

                chmod +x $HOME/bin/argocd

                echo "$HOME/bin" >> $GITHUB_PATH

            - name: Login Argocd Application
              shell: bash
              run: |
                argocd login ${{ secrets.ARGOCD_SERVER }} \
                --grpc-web \
                --insecure \ 
                --username ${{ secrets.ARGOCD_USERNAME }} \ 
                --password ${{ secrets.ARGOCD_PASSWORD }}
            - name: Sync Argocd Application
              shell: bash
              run: |
                argocd app sync python-app
